main: com.koletar.jj.chestkeeper.ChestKeeper
name: ${project.name}
version: ${project.version}
authors: [jjkoletar, mattgd]
softdepend: [Vault]
commands:
  chestkeeper:
    aliases: [ck, gp, vc, chest]
    description: Manage your ChestKeeper.
    usage: /chestkeeper <subcommand>